In [1]:
import numpy as np

Scalars are single values with 0 dimensions

In [2]:
s = np.array(5)

In [3]:
s.shape

()

In [4]:
x = s + 3

In [5]:
x

8

In [6]:
x.dtype

dtype('int64')

In [7]:
type(x)

numpy.int64

Vectors are similar to arrays. They hold multiple values in 1 dimension

In [8]:
v = np.array([1,2,3])

In [9]:
v.shape

(3,)

In [10]:
v[1]

2

In [11]:
v[1:]

array([2, 3])

Matrices can hold multiple arrays in 2 dimnesions

In [12]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
m.shape

(3, 3)

In [14]:
m[1][2]

6

Tensors are like matrices and vectors, but they can have more than 2 dimensions

In [15]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [16]:
t.shape

(3, 3, 2, 1)

You can change shape of data without changing the contents

In [17]:
v = np.array([1,2,3,4])

In [18]:
v.shape

(4,)

In [19]:
x = v.reshape(1,4)

In [20]:
v

array([1, 2, 3, 4])

In [21]:
x

array([[1, 2, 3, 4]])

In [22]:
x = v.reshape(4,1)

In [23]:
x

array([[1],
       [2],
       [3],
       [4]])